import type { Metadata } from "next";
import Link from "next/link";
import { Contact, LegalDoc, Table } from "@/components/consent/LegalDoc";
import { AUDIT_LOG_RETENTION, legalInfo } from "@/lib/legal";

export const metadata: Metadata = { title: "Privacy policy" };

export default function PrivacyPage() {
  const { operator, email } = legalInfo();
  return (
    <LegalDoc
      title="Privacy policy"
      intro={`This policy explains what personal data the Portal handles, why, who sees it and what rights you have. The Portal is run by ${operator} for a private Dungeons & Dragons group and its Discord server.`}
    >
      <h2>1. Who is responsible</h2>
      <p>
        {operator} decides why and how data is handled in the Portal and in the recorder bot it controls (the &ldquo;controller&rdquo;). Contact for anything in this policy: <Contact email={email} operator={operator} />.
      </p>

      <h2>2. What we handle</h2>
      <Table
        head={["Data", "Where it comes from", "Why", "Basis"]}
        rows={[
          [
            "Discord user id, display name, avatar link",
            "Discord, when you sign in",
            "Identify you, show your name, record who did what",
            "Legitimate interest in running the service; contract once you use it",
          ],
          [
            "Your roles in the campaign server",
            "Discord (scope guilds.members.read, read once per check)",
            "Decide whether you may enter and whether you are the DM",
            "Legitimate interest (access control and security)",
          ],
          [
            "Session cookie with an encrypted Discord access token",
            "Created at sign-in",
            "Keep you signed in for up to 12 hours; the token is revoked at sign-out",
            "Strictly necessary",
          ],
          [
            "Voice recordings and transcripts of game sessions, speaker labels, character names",
            "The recorder bot in the Discord voice channel, started by an admin",
            "Provide session recordings, transcripts and search to the group",
            "Legitimate interest of the group; participants are told before recording starts (see section 4)",
          ],
          [
            "Campaign content: NPCs, creatures, encounters, areas, rewards, notes, scenes, saved music links",
            "What the DM types or saves",
            "Run and prepare the game",
            "Contract / legitimate interest",
          ],
          [
            "Audit log: time, your Discord id, action, request path, result",
            "Generated by the Portal on every sign-in and bot action",
            "Security, abuse prevention, accountability",
            "Legitimate interest (security)",
          ],
          [
            "Theme, selected campaign, remembered channel ids, dice settings",
            "Your choices in the Portal",
            "Remember them on your device",
            "Consent for keeping them beyond the visit (see the cookie policy)",
          ],
        ]}
      />
      <p>
        The Portal does <strong>not</strong> ask for your email address or your Discord messages, and it has no analytics, advertising or tracking tools.
      </p>

      <h2>3. Who receives data</h2>
      <ul>
        <li>
          <strong>Discord Inc.</strong> signs you in, supplies your roles and hosts the voice channel. Discord&rsquo;s own{" "}
          <a href="https://discord.com/privacy" rel="noopener noreferrer">
            privacy policy
          </a>{" "}
          applies to that. Your browser also loads your avatar from Discord&rsquo;s content network, which shows Discord your IP address.
        </li>
        <li>
          <strong>Hosting and infrastructure.</strong> The Portal, the bot and their data run on a server operated by {operator}. Any provider hosting that server processes data only on the operator&rsquo;s instructions.
        </li>
        <li>
          <strong>Speech-to-text.</strong> Recordings are transcribed by a transcription service run by the operator. If that ever moves to an outside provider, this policy will say so before the change.
        </li>
        <li>
          <strong>Music sources.</strong> When the DM saves or plays a YouTube or SoundCloud link, the bot requests that link from the provider. No personal data about you is sent.
        </li>
        <li>
          Members of the campaign group can see the sessions, transcripts and campaign content the DM and admins make available to them. We do not sell personal data and do not share it for advertising.
        </li>
      </ul>

      <h2>4. Recording game sessions</h2>
      <p>
        The bot records the voice channel only when an admin starts a recording, and shows that it is recording. Speech is personal data. Whoever starts a recording must tell everyone in the channel first, and anyone who objects can ask not to be recorded, or leave the channel. If you do not want to be on record, tell the DM and the operator; we will stop recording you where we reasonably can, and delete the parts that involve you on request.
      </p>
      <p>
        Recordings and transcripts are kept until a DM moves the session to the trash and purges it, or the trash is emptied automatically after its retention period. Deleted audio and transcripts are removed from the Portal&rsquo;s data directory; copies in server backups age out with the backup schedule.
      </p>

      <h2>5. How long we keep data</h2>
      <ul>
        <li>Sign-in session: up to 12 hours, then you sign in again. Ends at once when you sign out.</li>
        <li>Consent record: 180 days, then you are asked again.</li>
        <li>Preference cookies and device storage: one year with your consent, otherwise until the browser session ends.</li>
        <li>Audit log: about {AUDIT_LOG_RETENTION}, then the host rotates it away.</li>
        <li>Recordings, transcripts and campaign content: until a DM deletes them, or until the operator closes the group.</li>
      </ul>

      <h2>6. Where data is stored and transferred</h2>
      <p>
        Data is stored on the operator&rsquo;s server. Discord processes sign-in data in the United States and elsewhere under its own safeguards. We do not otherwise send personal data outside the server. If a future feature needs a processor in another country, we will use an appropriate transfer mechanism and update this page.
      </p>

      <h2>7. Security</h2>
      <p>
        The Portal only admits members of the campaign server who hold an admin role, re-checks that permission while you are signed in, encrypts the session cookie, sends everything over HTTPS, applies a strict content security policy and rate limits actions. No system is perfectly secure; if a breach affecting you occurs we will tell you and the relevant authority as the law requires.
      </p>

      <h2>8. Your rights</h2>
      <p>
        Depending on where you live (for example under the GDPR, UK GDPR or KVKK) you can ask to access your data, correct it, delete it, restrict or object to its use, receive a copy in a portable form, and withdraw consent at any time (use <em>Cookie settings</em> in the footer; withdrawing does not affect what happened before). To use a right, contact <Contact email={email} operator={operator} />. We answer within one month. You may also complain to your local data protection authority.
      </p>

      <h2>9. Children</h2>
      <p>The Portal is not meant for anyone under 16 and we do not knowingly collect their data. Discord itself requires users to be at least 13. Tell us if a child&rsquo;s data is here and we will delete it.</p>

      <h2>10. Automated decisions</h2>
      <p>Access is decided automatically from your Discord roles. Nothing else is decided about you by automated means, and no profiling is done.</p>

      <h2>11. Changes</h2>
      <p>
        If we change how data is handled (for example by adding payments or a new provider) we will update this page and its date, and ask for consent again where the law requires it. See also the <Link href="/terms">terms</Link> and the <Link href="/cookies">cookie policy</Link>.
      </p>
    </LegalDoc>
  );
}
